### ISSUE TITLE
TextField height in iOS7 is truncated

### ISSUE THREAD

**Issue by 0xc00010ff** [freak4pc/SMTagField#6]
At runtime the textField appears to be about 20 points high. 
I tried to assign a frame manually in my view controller, and also tried to hardcode a 50 point height in the SMTagField implementation, but this did not work. 

Please let me know is I'm doing this wrong or if this is a bug, I'd really like to use this control without having to make my own.

**Comment by freak4pc** [comment]
Hey @f0x0r , 
This textField was mainly designed as a replacement to a regular sized UITextField which is the basic reason I've limited the height to 30 pt. 

If there would be enough demand I would add the option for resizing the height, It requires a tad of changes both to SMTagField and SMTag.

For now you can manually hard code the height. You need to change the "30" value to whatever you want in the methods `initWithFrame:`, `init` and `setFrame:`. You would probably also want to change the UITag frame to fit. 

Shai.
