### ISSUE TITLE
Limit number of tags

### ISSUE THREAD

**Issue by tdunham02** [freak4pc/SMTagField#7]
How could you limit the number of tags (ex. limit to 5 tags)?

(Great control by the way!)

**Comment by freak4pc** [comment]
Hey @tdunham02 ,
First of all thanks for the compliment :) 

There's currently no method to explicitly limit the number of tags but you can easily do that in the `-(void)tagField: tagAdded` delegate like that : 

``` obj-c
-(void)tagField:(SMTagField *)_tagField tagAdded:(NSString *)tag{
    if(tagField.tags.count > 5)
        tagField.tags       = [tagField.tags objectsAtIndexes: [NSIndexSet indexSetWithIndexesInRange: NSMakeRange(0, 5)]];
}
```

**Comment by tdunham02** [comment]
This helps, I added some code to prevent the tag from getting added into the array, but this is what I was looking for! Thank you!

**Comment by freak4pc** [comment]
A short update about this, I added a new delegate method `tagField:shouldAddTag:` that should help you do this in a more correct way. Its in the latest commit (v1.1 commit 0aa04e7). 

The example looks something like this: 

``` obj-c
-(BOOL)tagField:(SMTagField *)_tagField shouldAddTag:(NSString *)tag{
    // Limits to a maximum of 5 tags and doesn't allow to add a tag called "cat"
    if(_tagField.tags.count >= 5 ||
       [[tag lowercaseString] isEqualToString: @"cat"])
        return NO;

    return YES;
}
```
